# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

experience_register:
    path: /experiences
    controller: App\Infrastructure\Http\Controller\ExperienceController::register
    methods: [POST]

session_create:
    path: /sessions
    controller: App\Infrastructure\Http\Controller\SessionController::create
    methods: [POST]

reservation_reserve:
    path: /reservations
    controller: App\Infrastructure\Http\Controller\ReservationController::reserve
    methods: [POST]

reservation_cancel:
    path: /reservations/{id}/cancel
    controller: App\Infrastructure\Http\Controller\ReservationController::cancel
    methods: [POST]


